name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        echo "Building"
        mkdir -p build
        echo "Build information" > build/info.txt

    - name: Test
      run: |
        echo "Testing"
        if test -f build/info.txt; then
          echo "File exists: build/info.txt"
        else
          echo "File does not exist: build/info.txt"
          exit 1
        fi